server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Explicitly map .mjs to application/javascript
    include /etc/nginx/mime.types;
    types {
        application/javascript mjs;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:js|mjs|css)$ {
        try_files $uri =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        try_files $uri =404;
    }
}
